import Provider from "./Provider";
import BottomNav from "./components/Molecules/BottomNav/page";
import Sidebar from "./components/Molecules/SideBar/Sidebar";
import Sideboard from "./components/Molecules/SideBoard/SideBoard";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black">
        <Provider>
          {" "}
          <div className="bg-[url('/as.png')]">
            <div className="flex flex-col justify-start bg-black/80 text-white md:flex-row xl:justify-center">
              <Sidebar />
              {children}
              <BottomNav />
              <Sideboard />
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
