# Generated by Django 4.2.1 on 2023-06-19 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_delete_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
